### ISSUE TITLE
フレームワークの生のエラー画面が出る

### ISSUE THREAD

**Issue by yutanakano** [owl/owl#123]
記事を削除後に削除された記事のURLを叩くフレームワークの生のエラーが出ています

**Comment by fortkle** [comment]
おそらく404 Not Foundのエラーだと思います。.envで `APP_DEBUG=true` になっていると生のエラーが出るので出したくない場合は falseで..。

**Comment by fortkle** [comment]
@yutanakano 
そのあたりはドキュメント参照。
https://github.com/owl/owl/wiki/%E7%92%B0%E5%A2%83%E8%A8%AD%E5%AE%9A#app_debug-%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88true

**Comment by fortkle** [comment]
@yutanakano 
すみません、404 Not Foundエラーでなく修正が必要そうなエラーでした :bow: 

https://github.com/owl/owl/blob/master/app/Repositories/Fluent/ItemRepository.php#L55
で記事情報取得の後にチェックしてないのが原因ですね。

**Comment by sota1235** [comment]
500のハンドリングしてないのですね、必要であればやっちゃいます(上のとはまた別の問題ですが)

**Comment by fortkle** [comment]
EloquentからQuery Builderに雑に移行した時にできたバグです〜。

**Comment by sota1235** [comment]
https://github.com/owl/owl/pull/127

暇なときに…

**Comment by sota1235** [comment]
developブランチってどこにいらっしゃるんでしょう…

**Comment by fortkle** [comment]
また私がやってしまったパターンか... ごめんなさい :bow:

**Comment by fortkle** [comment]
@sota1235 
リリースのタイミングで delete branchボタンをポチッとしてしまったみたいです・・・。
restoreしました :bow:

**Comment by fortkle** [comment]
protected branch に指定done

**Comment by sota1235** [comment]
@fortkle あざっす！

**Comment by fortkle** [comment]
@sota1235 @yutanakano 
developブランチに修正PRをマージしました。
次のパッチリリースでリリースしますね！ご報告ありがとうございました！

**Comment by fortkle** [comment]
@yutanakano @sota1235 
リリースしたのでcloseしますね！
