### ISSUE TITLE
変更履歴ページの記事タイトルが古い

### ISSUE THREAD

**Issue by sota1235** [owl/owl#163]
`/items/${item_id}`ページと`/items/${item_id}/history`ページで表示される記事タイトルが違う場合があり、
おそらく`/history`の方が途中でタイトル変更した場合の古いデータが残っている…？

**Comment by fortkle** [comment]
https://github.com/owl/owl/blob/master/resources/views/items/history.blade.php#L26

最新1件のitem_historyのtitleを表示してるからだね。
`/history`ページでも itemを取得してきて表示するようにするとなおるっぽい。

**Comment by fortkle** [comment]
@sota1235 こちらリリース終わりました!
