### ISSUE TITLE
Markdownのリアルタイムプレビュー

### ISSUE THREAD

**Issue by sota1235** [owl/owl#22]
あると嬉しそうな気がするんですけどいかがでしょう
(今のカラムだとタブで見れるとかが無難…？)

**雑なイメージ図**
![イメージ](https://i.gyazo.com/846642f1663a5a4f563a5b0f57d8aab2.png)

**Comment by fortkle** [comment]
あると嬉しいですね。
タブで切り替えられるイメージも良いと思います。

**Comment by sota1235** [comment]
あざます！頑張ってみます

**Comment by sota1235** [comment]
プルリクdone

**Comment by sota1235** [comment]
ヤッターーーー!!!
