### ISSUE TITLE
スタイルシートをStylusで管理する

### ISSUE THREAD

**Issue by sota1235** [owl/owl#24]
やるなら今感あると思うのですが、どうですかね

**Comment by hanhan1978** [comment]
Stylus

**Comment by sota1235** [comment]
altCSSにわか勢なので推薦理由が知りたいです(｀・ω・´)！！

**Comment by hanhan1978** [comment]
つい最近、新しいPJでsass使おうとしたら、「そこはstylusだろう！」とフロントエンドエンジニアーズに言われたためです！！！

彼いわく、今はstylusが一番ナウい。sassは元々の出自がrubyからなので、nodeから生まれたstylusが一番筋が良い！とのことです。

**Comment by sota1235** [comment]
(´・ω・｀)

**Comment by sota1235** [comment]
ここは高野総隊長に判断を…

**Comment by hanhan1978** [comment]
総隊長に従います！

**Comment by fortkle** [comment]
デザインリニューアル時に良さそうなやつを選びますー
（今の流れだとstylusよさそう）
