### ISSUE TITLE
ユーザーごとにアクションの通知を受け取ることができる

### ISSUE THREAD

**Issue by fortkle** [owl/owl#35]
Facebookのように、自分が書いた記事にコメントされたり、いいね！が押されたり、ストックされたりしたら通知アイコンなどで通知を受け取れると嬉しい。

**Comment by sota1235** [comment]
これ割と最近欲しいです…|ω・)

**Comment by fortkle** [comment]
懸念点

・なるべくシンプルでポータブルな仕組みにしたい→適当に実装すると後に引けない
・sqliteの限界が来るのを遅らせるためにDBは軽めに → 通知履歴テーブルを作るとDBの肥大化が推測される
・本当にやりたいのは「コメントに反応したい」など限られたパターンでは？ → webhookでslack連携できれば解決しそう

**Comment by sota1235** [comment]
webhookで実装してSlackっていうのはストリーム的に流れてくるイメージですか？
だとすると「自分の記事にコメントがついた」ことを見逃す可能性が高い気がするのですよね。
メンションを飛ばすという手もありますが、Slackでのアカウント名で登録してるとも限らないので結構つらい気がします…(にしてもwebhookは欲しいですね)。

ポータビリティの優先度は理解してるつもりなんですが、例えば以下の様な感じはどうでしょう。

- 通知以外の現行の機能は現在のREADMEの手順ですぐ利用可能
- オプションとして、使いたい人はredisやmongo等でセットアップして通知機能使っていいよ！と案内する

ただこうすると何をオプション(?)に含めるかで今後どうなってくかがまた悩ましいですが…。

もしくはメールアドレスが登録項目にあったのでデフォルトで通知をオフにしてQueueを利用してメール通知もありかもしれません。
ビルド手順が1つ増えますがこれならDBを圧迫せず、実装もシンプルで済むと思います！

**Comment by localdisk** [comment]
シンプルでポータブル…結構難しいですね。制限なければPusher使ってwebsockeからのデスクトップ通知なのですが。 うーむ…。

**Comment by fortkle** [comment]
通知先の落とし所としてメールは良さそうだね。結構シンプルにできそうだし、既にパスワードリマインダー機能でメール周り使ってるし！

**Comment by sota1235** [comment]
正月ゆっくりできるしメールの方向性で作ってみます

- [ ] メールの受信設定ができる
  - 設定ページでメールの通知を受け取る設定を用意、デフォルトだとオフが望ましい？
- [ ] 各種アクション時にキューにメール送信ジョブを突っ込む
  - メール送信したいアクションが散り散りになるのでイベント等でさばくと保守しやすいのかな…？(何かアイディアあればください)

**Comment by fortkle** [comment]
パスワードリマインダーもデフォルト機能OFFなので、メール周りの機能はデフォルトOFFでいいかな。

通知メール系ならイベントでまとめた方がいいかもね。その方向性で。

**Comment by fortkle** [comment]
（「ストック」がしれっと「お気に入り(favorite)」にしてたなんて言えやしないよ..）

**Comment by sota1235** [comment]
(途中で気づいてクラス名変えたでござる…)

**Comment by fortkle** [comment]
（既存の「お気に入り関連のStock」はFavorite的なやつに今度変えます...はい...やります....）

（ただしdbのtable名は変えられない...）
