### ISSUE TITLE
MySQLに対応する

### ISSUE THREAD

**Issue by fortkle** [owl/owl#38]
configの設定を変えればほとんどの機能は使えるが、全文検索だけはSQLiteに依存しているので改修が必要

**Comment by hanhan1978** [comment]
MySQL5.7のみ対応してみました。
FullText検索用のテーブルを作成するのではなく、ngramの検索インデックスを作成してます。

対応の方向性をとりあえず確認して貰いたいです。
MySQLドライバーに切り替えて、behatのテストがパスすることは確認済みです。

**Comment by sota1235** [comment]
よさ！よさ！

**Comment by hanhan1978** [comment]
この先、どしたら良いでしょう？ とりあえず現状まとめです。
- travis mysql 5.7 => とても大変
- mysql5.6以下で全文検索 => とても大変
- デフォルトはsqliteなので、後方互換は大丈夫
- ReadMeにMySQL設定については書くべきか

**Comment by sota1235** [comment]
- travis mysql 5.7 => とても大変 / mysql5.6以下で全文検索 => とても大変
ツライ。
CIの時の話であればDBのテストしてもあれですしTravis上ではモックしたい…

- ReadMeにMySQL設定については書くべきか
READMEにはOptional的な扱いでMySQLもいけますよといった感じで書いておくって感じがよい気がします〜

コードベースではLGTMなので週末動作確認して問題なさげならマージしたい気持ちです！
いかがでしょ @fortkle

**Comment by fortkle** [comment]
PRありがとうございます！

・Travisではsqliteでのテストでいいと思います
・5.6以下で全文検索はめっちゃ辛いので ≧5.7 サポートでいいと思います
・sota1235と同じく、READMEには対応DBとしてMySQLも列挙し、詳しい設定が必要ならwikiで補足がいいかなと思います
・まだコード見れてないのでマージ可否はそれから

以上です！
@sota1235 @hanhan1978
