### ISSUE TITLE
rspecのテストをbehatに書き換える

### ISSUE THREAD

**Issue by fortkle** [owl/owl#48]
久々にrspec動かしてみたら動かなくて色々つらい。
この際、behat等のPHP製のものに移行したい。

**Comment by sota1235** [comment]
(Laravel5.1にすればPHPUnitで一元化できますよ…)

**Comment by sota1235** [comment]
:cat:

**Comment by fortkle** [comment]
Laravel5.0だとPHPUnitに一元化できないん？？

あと5.1はPHP5.5↑↑だからちょっとね。

**Comment by sota1235** [comment]
5.0だとドキュメントにはのってないのですよ。もしかしたら使えるかもしれないけど。。
バージョンの壁の悲しみ😷

**Comment by fortkle** [comment]
一旦、スモークテストだけ作成。

**Comment by fortkle** [comment]
jsが実行できなくなったので下記テストができなくなったけど一旦完了。

- いいねボタン
- コメント機能
- 投稿の削除
