### ISSUE TITLE
EloquentからQuery Builderに移行

### ISSUE THREAD

**Issue by fortkle** [owl/owl#72]
タイトルの通り。

**Comment by sota1235** [comment]
![](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR6EB4ScQY4CLl8tgDPCfeu1nods_FwJc6RfgrVexhPwN2N0TuceA)

**Comment by fortkle** [comment]
Eloquentが汚物なのではない、操れない我々が汚物なのだ...（いま良いこと言った）

**Comment by sutoh** [comment]
ActiveRecordと同じ道を歩んでいるようにみえますな。
http://ruby-rails.hatenadiary.com/entry/20150428/1430154446

**Comment by sota1235** [comment]
お仕事休憩だったのでコメントでちょっかい出してみました

**Comment by fortkle** [comment]
done.
