### ISSUE TITLE
JS, CSSライブラリをnpm管理する

### ISSUE THREAD

**Issue by sota1235** [owl/owl#74]
時代的にも将来的な保守的にもBootstrapやjqueryやhighlight.jsもろもろバージョン管理した方がよいと思うのです。
`setup_app.sh`が追加されたのでGulpの設定やらをしっかりやって`npm i && npm build`を追記してって感じが一番短く綺麗に済むと思うんですが、ポータビリティ意識する際に問題になるとしたらNode.jsのインストールが不可欠になる点だと思います。
そこらへんについて議論できればと :dango:

**Comment by sota1235** [comment]
(npm管理しないにしてもライブラリ系ファイルと通常ファイルの区別はフォルダ等でつけてしまいたい)

**Comment by fortkle** [comment]
> 時代的にも将来的な保守的にもBootstrapやjqueryやhighlight.jsもろもろバージョン管理した方がよいと思うのです。

agree

> ポータビリティ意識する際に問題になるとしたらNode.jsのインストールが不可欠になる点だと思います。

正直、今後開発する上でNode使えないと辛すぎるので解禁してしまって良いと思います（ポータビリティの問題は配布時の問題なのでまた別issueかなと）

**Comment by sota1235** [comment]
解禁٩(ˊᗜˋ*)و

そしたら #35 で出すプルリクに混ぜてしまいますね。
既存のものに関してはまた別プルリクを作ります！

**Comment by fortkle** [comment]
@sota1235 GOGO
