### ISSUE TITLE
[IE11] 通知メール送信設定の表示崩れ

### ISSUE THREAD

**Issue by sota1235** [owl/owl#81]
IE11で表示崩れを確認したので直す。

![](https://i.gyazo.com/690842fe35986226b0ae4ac3f0dfa7ec.png)

**Comment by fortkle** [comment]
ワロタ...ワロタ....

**Comment by sota1235** [comment]
IEつらい(^q^)

**Comment by fortkle** [comment]
IE11なので言い訳できません..!!

**Comment by kubotak-is** [comment]
```
#main .mail-checkbox-form {
    width: 100%;
    height: 50px
    margin: 15px 0;
}
```
取り急ぎこれでIE11は崩れなさそうだけど、レスポンシブでスマホ要レイアウトに切り替わると崩れますね。HTML構造から修正したほうが良さそう

**Comment by fortkle** [comment]
http://www.itcowork.co.jp/blog/?p=3258

IE11確認するの面倒...

**Comment by sota1235** [comment]
放置しててサーセン…
調べたらスタイル崩れちゃってる`bootstrap-switcher`はIE8まで対応してるらしいのでそれが間違いじゃなければ僕のライブラリの使い方が間違ってる可能性が高い気がします。
(会社じゃないとIEないから作業が進まない :cry: )

**Comment by fortkle** [comment]
@sota1235 
これ、修正お願いしても良いですか...
IEでの確認が思った以上につらそうで....

**Comment by sota1235** [comment]
やりましょう！

**Comment by sota1235** [comment]
CSSできなすぎて難航してるんですが何かアドバイスあったりしませんか… orz @kubotak-is

**Comment by fortkle** [comment]
@sota1235 IE対応企業！！！ :pray:

**Comment by sota1235** [comment]
おうちにIEがほすぃー…

**Comment by fortkle** [comment]
@sota1235 駆逐してくる

![ie11_-_win7__running_](https://cloud.githubusercontent.com/assets/1576804/14587094/f75c351c-04e6-11e6-9d5e-7f69948f59ea.png)

**Comment by fortkle** [comment]
- 整列するように修正
- ボタンサイズをバランスを見て少し小さめに変更

# pc
![ie11_-_win7__running_](https://cloud.githubusercontent.com/assets/1576804/14587366/dc94d382-04ec-11e6-8c4d-bc63148d1f4f.png)

# sp
![___owl](https://cloud.githubusercontent.com/assets/1576804/14587380/0ea6dece-04ed-11e6-8a5c-c4f9d37aa867.png)

**Comment by fortkle** [comment]
@sota1235 @kubotak-is 
修正完了したので次のリリースで出しますね。
協力あざっした！ 🙇

**Comment by fortkle** [comment]
（SP、中途半端対応だからサイドバーの「記事を公開する」ボタンが最下部に出てなんかヤバイ・・・）

**Comment by sota1235** [comment]
ほんとすいませんありがとうございます。。。
