### ISSUE TITLE
{FQDN}/items/hogeページ内の「この記事をお気に入りする」をクリックした後も文言が同じ

### ISSUE THREAD

**Issue by ktarow** [owl/owl#86]
https://github.com/owl/owl/blob/master/resources/views/items/show.blade.php#L98

Ajaxっぽいのでリクエストが返ってきたときには、「お気に入りを解除する」に変更すべきかと

**Comment by fortkle** [comment]
「いいね！」も同様ですねぇ... git blame...

**Comment by sota1235** [comment]
git blame見てないけど多分ぼくです

**Comment by sota1235** [comment]
memo: jQuery UIの`button()`メソッドが非同期で走ってるっぽい…？
でもAPIドキュメントを見る限りcallbackを渡す方法がなさげ…
