### ISSUE TITLE
複数枚画像をアップロードしたら、投稿ボタンがloadingのまま動かなくなった

### ISSUE THREAD

**Issue by ktarow** [owl/owl#94]
アップロードした画像数は4枚

**Comment by ktarow** [comment]
画像自体は登録されている

**Comment by fortkle** [comment]
再現取れました。 @sota1235 案件かな？

**Comment by ktarow** [comment]
#46 案件ですかね？

**Comment by fortkle** [comment]
いやそれもまだ解決してないけど別問題だと思う。
画像アップロードの処理に 投稿ボタンが反応してしまっている。

**Comment by sota1235** [comment]
woops...確認しますね(明日の夜か明後日あたりに…)

**Comment by sota1235** [comment]
うむー、手元で確認できない…

**Comment by fortkle** [comment]
@ktarow 
対応リリースしたのでcloseしますね！
