### ISSUE TITLE
記事のh1タグの直後に書いたpタグと文字がそろっていないのが気になる

### ISSUE THREAD

**Issue by ktarow** [owl/owl#95]
h1タグは、
```
padding: 3px 10px;
```
なのに対し、

pタグにはpaddingがふられていないので、文字がずれて気になる

**Comment by ktarow** [comment]
暫定的に
```
h1: {
  padding: 3px 10px;
}

.page_body {
  padding: 3px;
}
```

にすると割ときれいに見れるがそろっていないので、ちゃんとそろえたい。

**Comment by fortkle** [comment]
@ktarow 
ちょっと確認。

### 現状
![2016-02-21 10 33 13](https://cloud.githubusercontent.com/assets/1576804/13200349/28ea3908-d887-11e5-902c-fb9aaf9a1430.png)

### こうちゃんcss
```
h1: {
  padding: 3px 10px;
}

.page_body: {
  padding: 3px;
}
```
![2016-02-21 10 37 22](https://cloud.githubusercontent.com/assets/1576804/13200350/301a0e60-d887-11e5-8b1b-df74a6c98bfd.png)

### こっちの方がよい？
```
#contents #main .page-body p {
  padding-left: 3px;
}
```
![2016-02-21 10 37 06](https://cloud.githubusercontent.com/assets/1576804/13200351/3eee8bbe-d887-11e5-9a89-ea04e07b8648.png)

**Comment by ktarow** [comment]
一番下のがいいですね！

**Comment by fortkle** [comment]
@ktarow おーけー、一番下で修正入れる。

**Comment by fortkle** [comment]
developにマージしたので次のリリースで出します。
